services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend/app:/app
    ports:
      - 3000:3000
    depends_on:
      - backend
    env_file:
      - .env

  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  test_db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_mydb

  postfix:
    image: catatnight/postfix
    env_file:
      - .env

volumes:
  postgres_data: