import AuthProtected from "@/components/auth/AuthProtected"
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mail-Relay</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthProtected>
        <h1>esto no deberia verse si no estas logueado</h1>
      </AuthProtected>
    </>
  );
}