name: Dockerized Python CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file from template
        run: cp template.env .env

      - name: Build Docker image
        run: docker build -t my-docker-image ./backend

      - name: Build and Run tests with Docker Compose
        run: docker-compose up -d backend db

      - name: Run tests
        run: docker-compose exec -T backend pytest app/tests/
